services:
  # Сервис для разработки (hot reload)
  app-dev:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      # Монтируем исходники для hot reload
      - .:/app
      # Исключаем node_modules, чтобы не перезаписывать контейнерные
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    profiles:
      - dev
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  # Сервис для продакшена с nginx
  app-prod:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443" # Опционально для HTTPS
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    profiles:
      - prod
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"